version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORTS}

  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - ${MONGO_PORTS}
    volumes:
      - mongodb_data:/data/db
  rabbitmq:
    image: rabbitmq:4.1-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - ${RABBITMQ_PORT}
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    volumes:
      - rabbitmq_data:/data/rabbitmq

  core_microservice:
    build:
      context: .
      dockerfile: apps/core_microservice/Dockerfile
    env_file:
      - apps/core_microservice/.env
    depends_on:
      - postgres
      - mongodb
    ports:
      - "${CORE_PORT}:${CORE_PORT}"

  auth_microservice:
    build:
      context: .
      dockerfile: apps/auth_microservice/Dockerfile
    env_file:
      - apps/auth_microservice/.env
    depends_on:
      - mongodb
      - core_microservice
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"

  frontend:
    build:
      context: .
      dockerfile: apps/clients_app/Dockerfile
    env_file:
      - apps/clients_app/.env
      - apps/clients_app/.env.local
    depends_on:
      - core_microservice
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"

volumes:
  postgres_data:
  mongodb_data:
  rabbitmq_data:
