version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: Innogram
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      
    ports:
      - "5434:5432"
    
  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: auth
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db=value
  core_microservice:
    build:
      context: .
      dockerfile: apps/core_microservice/Dockerfile
    env_file:
      - ./apps/core_microservice/.env
    depends_on:
      - postgres
      - mongodb
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Innogram
      MONGODB_URI: mongodb://admin:password@mongodb:27017/auth?authSource=admin
  frontend:
    build:
      context: .
      dockerfile: apps/clients_app/Dockerfile
    depends_on:
      - core_microservice
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
volumes:
  postgres_data:
  mongodb_data: