import { ApiProperty } from "@nestjs/swagger"

export class createUserDto {
  @ApiProperty({
    description:'id is generated by default in prisma'
  })
  id?:string
  @ApiProperty({
    description:"Role is enum and can only have one of two values user or admin"
  })
  role?:"user" | "admin"
  @ApiProperty({
    description:"Disabled is boolean that tells if account is disabled by default is false"
  })
  disabled? : false
  created_by_id?: string | null
  updated_by_id?: string | null
}